// Import the pre-built bundle generated by esbuild in build-vercel.js.
// This avoids Vercel's runtime having to resolve TypeScript workspace packages.
// @ts-ignore - bundle has no TypeScript declarations
import app from './app.bundle.js';

// Configure Vercel to not parse the body natively, 
// allowing Express's express.json() to consume the raw stream.
export const config = {
  api: {
    bodyParser: false,
  },
};

// Export the Express app as a Vercel Serverless Function handler.
export default app;

